# Generated by Django 4.0 on 2021-12-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_des', models.CharField(max_length=300)),
                ('slide_image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
