# Generated by Django 4.0 on 2021-12-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidemodel',
            name='slide_image',
            field=models.ImageField(blank=True, upload_to='slids/'),
        ),
    ]
