# Generated by Django 4.0 on 2021-12-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0002_alter_slidemodel_slide_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=200)),
                ('skill_Quantity', models.IntegerField(max_length=3)),
            ],
        ),
    ]
