# Generated by Django 4.0 on 2021-12-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0004_alter_skill_skill_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=200)),
                ('service_des', models.CharField(max_length=500)),
                ('read_more', models.CharField(max_length=20)),
            ],
        ),
    ]
