# Generated by Django 4.0 on 2021-12-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0005_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('subject', models.CharField(max_length=120, verbose_name='Subject')),
                ('appointment_date', models.DateField(verbose_name='Appointment Date')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.IntegerField(verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
