# Generated by Django 4.0 on 2021-12-23 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0006_appoinment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department_galary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_title', models.CharField(max_length=100)),
                ('dep_sub_title', models.CharField(max_length=500)),
                ('dep_image', models.ImageField(blank=True, upload_to='dep_images/')),
                ('department', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='homeApp.department')),
            ],
        ),
    ]
