# Generated by Django 4.0 on 2021-12-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0009_department_dep_image_department_dep_short_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=150)),
                ('doc_image', models.ImageField(blank=True, upload_to='dep_images/')),
                ('dep_title', models.CharField(max_length=50)),
                ('fb_link', models.URLField(blank=True, max_length=254)),
                ('tw_link', models.URLField(blank=True, max_length=254)),
                ('li_link', models.URLField(blank=True, max_length=254)),
                ('doc_schedule', models.ManyToManyField(related_name='doc_schedule', to='homeApp.Schedule')),
            ],
        ),
    ]
