# Generated by Django 4.0 on 2021-12-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0011_rename_dep_title_doctor_doc_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_schedule',
            field=models.ManyToManyField(related_name='doct_schedule', to='homeApp.Schedule'),
        ),
    ]
