# Generated by Django 4.0 on 2021-12-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0013_clint_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_count', models.IntegerField(verbose_name='Service Count')),
                ('services_title', models.CharField(max_length=50, verbose_name='Service')),
            ],
        ),
    ]
